server:
  port: 81
spring:
  application:
    name: member-service-consumer-80
#  zipkin:
#    base-url: http://localhost:9411
#  sleuth:
#    sampler:
#      probability: 1
#
##配置eureka-client
#eureka:
#  client:
#    register-with-eureka: true #将自己注册到Eureka-Server
#    fetch-registry: true
#    service-url:
#      #表示将自己注册到哪个eureka-server
#      #这里我们将本微服务注册到EurekaServer 集群，使用逗号间隔
#      #defaultZone: http://localhost:9001/eureka
#      defaultZone: http://eureka9001.com:9001/eureka,http://eureka9002.com:9002/eureka